[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.23"
dotenv = "0.15.0"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
